server:
  port: 8087
  
spring:
  jpa:
    hibernate:
      ddl-auto: none
# H2
# Datasource
  h2:
    console:
      enabled: true
      path: /h2db
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver 